### ISSUE TITLE
丢失两个存在于 Rena 但没有文件的谱

### ISSUE THREAD

**Issue by Taskeren** [EDTA-gif/dynamite-charts-repository#7]
1. Operation Spectrum [Short Edit](Dr. i0ntempest w BPDF)
2. Night Cruiser R3 [Dynamite Edit](Commander i0ntempest)

**Comment by EDTA-gif** [comment]
那两张是原数据提供者i0ntempest自己写的test谱，于第一次上传中误传至仓库
rena中的数据将在检查后删除，感谢提醒
